title: ""  # 页面标题
baseurl: ""  # 确保这是空的，避免路径问题

markdown: kramdown  # 使用Markdown渲染引擎

theme: jekyll-theme-cayman  # 使用Jekyll内置的主题

# 强制显示 README.md 内容
exclude:
  - "index.md"  # 确保 GitHub Pages 仅使用 README.md，而不是任何其他 index.md 文件
  - "index.html"  # 确保 index.html 不会被渲染，默认显示 README.md
